apiVersion: v1
kind: Secret
metadata:
  name: spring-petclinic-postgres-secret
  labels:
    app: spring-petclinic-git
type: Opaque
data:
  password: cGV0Y2xpbmlj
  # echo -n 'petclinic' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-petclinic-postgres-configmap
  labels:
    app: spring-petclinic-git
data:
  database: petclinic
  user: petclinic
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spring-petclinic-postgres-pvc
  labels:
    app: spring-petclinic-git
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-postgres-deployment
  labels:
    app: spring-petclinic-git
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'registry.redhat.io/rhel9/postgresql-15@sha256:d5f3d496ecd55688e384cc0627700a97af6924582123bcf00749c375724af3de'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRESQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-postgres-configmap
                  key: database
            - name: POSTGRESQL_USER
              valueFrom:
                configMapKeyRef:
                  name: spring-petclinic-postgres-configmap
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: spring-petclinic-postgres-secret
                  key: password
          volumeMounts:
            - mountPath: /var/lib/pgsql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: spring-petclinic-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-postgres-service
  labels:
    app: spring-petclinic-git
spec:
  ports:
    - port: 5432
  selector:
    app: postgres
