apiVersion: v1
kind: Secret
metadata:
  name: spring-petclinic-postgres-secret
  labels:
    app: spring-petclinic-git
type: Opaque
data:
  password: cGV0Y2xpbmlj
  # echo -n 'petclinic' | base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-petclinic-postgres-configmap
  labels:
    app: spring-petclinic-git
data:
  url: jdbc:postgresql://spring-petclinic-postgres-service.s2i-spring-petclinic-database/petclinic
  database: petclinic
  user: petclinic
